### ISSUE TITLE
Unable to install modules using rexify command

### ISSUE THREAD

**Issue by eskaaren** [RexOps/modules.rexify.org#2]
rexify --use=Rex::Ext::Fail returns 404 and JSON {"ok":0}.

Seems like it is failing for all modules according to discussion on irc.

**Comment by ferki** [comment]
@eskaaren: thanks for reporting, and sorry for the delay, but this should be fixed now. Feel free to reopen if you still have problems with it.

FTR: the problem was about a misplaced file (which contains the module dependency tree).
